SELECT * FROM GROUPS;
SELECT * FROM STUDENTS;

INSERT INTO GROUPS(NAME) VALUES ('iitp_353503');
INSERT INTO GROUPS(NAME) VALUES ('iitp_453503');
INSERT INTO GROUPS(ID, NAME) VALUES (1,'iitp_253503');
INSERT INTO STUDENTS (STUDENT_NAME, GROUP_ID) VALUES ('Artsiom', 1);
INSERT INTO STUDENTS (ID, STUDENT_NAME, GROUP_ID) VALUES (1, 'Vasya', 1);

UPDATE GROUPS SET NAME = 'iitp_353503' WHERE NAME ='iitp_453503';
UPDATE STUDENTS SET ID = 1 WHERE ID = 2;

COMMIT;