CREATE OR REPLACE TRIGGER GROUPS_AUTO_INC_BEFORE_INSERT
BEFORE INSERT ON GROUPS
FOR EACH ROW
DECLARE
    v_max_id NUMBER;
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT NVL(MAX(ID), 0) INTO v_max_id FROM GROUPS;
        :NEW.ID := v_max_id + 1;
    END IF;
END GROUPS_AUTO_INC_BEFORE_INSERT;

CREATE OR REPLACE TRIGGER STUDENTS_AUTO_INC_BEFORE_INSERT
BEFORE INSERT ON STUDENTS
FOR EACH ROW
DECLARE
    v_max_id NUMBER;
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT NVL(MAX(ID), 0) INTO v_max_id FROM STUDENTS;
        :NEW.ID := v_max_id + 1;
    END IF;
END STUDENTS_AUTO_INC_BEFORE_INSERT;
