SELECT * FROM STUDENTS;
SELECT * FROM GROUPS;

INSERT INTO STUDENTS (STUDENT_NAME, GROUP_ID) VALUES ('Artsiom', 1);

UPDATE STUDENTS SET STUDENT_NAME = 'Vasya' WHERE STUDENT_NAME = 'Artsiom';

DELETE STUDENTS WHERE STUDENT_NAME = 'Vasya';

COMMIT;