import pandas as pd
import matplotlib.pyplot as plt


def binary_plot(csv_file_amd_smt: str, csv_file_intel_smt: str, csv_file_amd: str, csv_file_intel: str):
    data_frame_amd_smt = pd.read_csv(csv_file_amd_smt)
    data_frame_amd = pd.read_csv(csv_file_amd)
    data_frame_intel_smt = pd.read_csv(csv_file_intel_smt)
    data_frame_intel = pd.read_csv(csv_file_intel)

    # 1. График для последовательной версии (seq)
    plt.figure(figsize=(10, 6))
    plt.plot(data_frame_amd_smt['Бинарные_Цели'], data_frame_amd_smt['Бинарный_Посл'], 'ro-', label='Amd Ryzen 7 5800H SMT')
    plt.plot(data_frame_amd['Бинарные_Цели'], data_frame_amd['Бинарный_Посл'], 'yo-', label='Amd Ryzen 7 5800H No SMT')
    plt.plot(data_frame_intel_smt['Бинарные_Цели'], data_frame_intel_smt['Бинарный_Посл'], 'bo-', label='Intel i7 12700H SMT')
    plt.plot(data_frame_intel['Бинарные_Цели'], data_frame_intel['Бинарный_Посл'], 'co-', label='Intel i7 12700H No SMT')
    plt.xlabel('Количество поисков')
    plt.ylabel('Время (микросекунды)')
    plt.title('Последовательная версия бинарного поиска (seq)')
    plt.legend()
    plt.grid(True)
    plt.savefig('binary_seq_comparison.png', dpi=300, bbox_inches='tight')
    plt.show()

    # 2. График для версии с ядрами (core)
    plt.figure(figsize=(10, 6))
    plt.plot(data_frame_amd_smt['Бинарные_Цели'], data_frame_amd_smt['Бинарный_Ядро'], 'ro-', label='Amd Ryzen 7 5800H SMT')
    plt.plot(data_frame_amd['Бинарные_Цели'], data_frame_amd['Бинарный_Ядро'], 'yo-', label='Amd Ryzen 7 5800H No SMT')
    plt.plot(data_frame_intel_smt['Бинарные_Цели'], data_frame_intel_smt['Бинарный_Ядро'], 'bo-', label='Intel i7 12700H SMT')
    plt.plot(data_frame_intel['Бинарные_Цели'], data_frame_intel['Бинарный_Ядро'], 'co-', label='Intel i7 12700H No SMT')
    plt.xlabel('Количество поисков')
    plt.ylabel('Время (микросекунды)')
    plt.title('Версия на одном ядре бинарного поиска (core)')
    plt.legend()
    plt.grid(True)
    plt.savefig('binary_core_comparison.png', dpi=300, bbox_inches='tight')
    plt.show()

    # 3. График для OpenMP версии (omp)
    plt.figure(figsize=(10, 6))
    plt.plot(data_frame_amd_smt['Бинарные_Цели'], data_frame_amd_smt['Бинарный_OMP'], 'ro-', label='Amd Ryzen 7 5800H SMT')
    plt.plot(data_frame_amd['Бинарные_Цели'], data_frame_amd['Бинарный_OMP'], 'yo-', label='Amd Ryzen 7 5800H No SMT')
    plt.plot(data_frame_intel_smt['Бинарные_Цели'], data_frame_intel_smt['Бинарный_OMP'], 'bo-', label='Intel i7 12700H SMT')
    plt.plot(data_frame_intel['Бинарные_Цели'], data_frame_intel['Бинарный_OMP'], 'co-', label='Intel i7 12700H No SMT')
    plt.xlabel('Количество поисков')
    plt.ylabel('Время (микросекунды)')
    plt.title('OpenMP версия бинарного поиска (omp)')
    plt.legend()
    plt.grid(True)
    plt.savefig('binary_omp_comparison.png', dpi=300, bbox_inches='tight')
    plt.show()

    # 4. График для GPU версии (igpu)
    plt.figure(figsize=(10, 6))
    plt.plot(data_frame_amd_smt['Бинарные_Цели'], data_frame_amd_smt['Бинарный_GPU'], 'ro-', label='Amd Ryzen 7 5800H SMT')
    plt.plot(data_frame_amd['Бинарные_Цели'], data_frame_amd['Бинарный_GPU'], 'yo-', label='Amd Ryzen 7 5800H No SMT')
    plt.plot(data_frame_intel_smt['Бинарные_Цели'], data_frame_intel_smt['Бинарный_GPU'], 'bo-', label='Intel i7 12700H SMT')
    plt.plot(data_frame_intel['Бинарные_Цели'], data_frame_intel['Бинарный_GPU'], 'co-', label='Intel i7 12700H No SMT')
    plt.xlabel('Количество поисков')
    plt.ylabel('Время (микросекунды)')
    plt.title('GPU версия бинарного поиска (igpu)')
    plt.legend()
    plt.grid(True)
    plt.savefig('binary_igpu_comparison.png', dpi=300, bbox_inches='tight')
    plt.show()

def linear_plot(csv_file_amd_smt: str, csv_file_intel_smt: str, csv_file_amd: str, csv_file_intel: str):
    data_frame_amd_smt = pd.read_csv(csv_file_amd_smt)
    data_frame_amd = pd.read_csv(csv_file_amd)
    data_frame_intel_smt = pd.read_csv(csv_file_intel_smt)
    data_frame_intel = pd.read_csv(csv_file_intel)

    # 1. График для последовательной версии (seq)
    plt.figure(figsize=(10, 6))
    plt.plot(data_frame_amd_smt['Линейные_Цели'], data_frame_amd_smt['Линейный_Посл'], 'ro-', label='Amd Ryzen 7 5800H SMT')
    plt.plot(data_frame_amd['Линейные_Цели'], data_frame_amd['Линейный_Посл'], 'yo-', label='Amd Ryzen 7 5800H No SMT')
    plt.plot(data_frame_intel_smt['Линейные_Цели'], data_frame_intel_smt['Линейный_Посл'], 'bo-', label='Intel i7 12700H SMT')
    plt.plot(data_frame_intel['Линейные_Цели'], data_frame_intel['Линейный_Посл'], 'co-', label='Intel i7 12700H No SMT')
    plt.xlabel('Количество поисков')
    plt.ylabel('Время (микросекунды)')
    plt.title('Последовательная версия линейного поиска (seq)')
    plt.legend()
    plt.grid(True)
    plt.savefig('linear_seq_comparison.png', dpi=300, bbox_inches='tight')
    plt.show()

    # 2. График для версии с ядрами (core)
    plt.figure(figsize=(10, 6))
    plt.plot(data_frame_amd_smt['Линейные_Цели'], data_frame_amd_smt['Линейный_Ядро'], 'ro-', label='Amd Ryzen 7 5800H SMT')
    plt.plot(data_frame_amd['Линейные_Цели'], data_frame_amd['Линейный_Ядро'], 'yo-', label='Amd Ryzen 7 5800H No SMT')
    plt.plot(data_frame_intel_smt['Линейные_Цели'], data_frame_intel_smt['Линейный_Ядро'], 'bo-', label='Intel i7 12700H SMT')
    plt.plot(data_frame_intel['Линейные_Цели'], data_frame_intel['Линейный_Ядро'], 'co-', label='Intel i7 12700H No SMT')
    plt.xlabel('Количество поисков')
    plt.ylabel('Время (микросекунды)')
    plt.title('Версия на одном ядре линейного поиска (core)')
    plt.legend()
    plt.grid(True)
    plt.savefig('linear_core_comparison.png', dpi=300, bbox_inches='tight')
    plt.show()

    # 3. График для OpenMP версии (omp)
    plt.figure(figsize=(10, 6))
    plt.plot(data_frame_amd_smt['Линейные_Цели'], data_frame_amd_smt['Линейный_OMP'], 'ro-', label='Amd Ryzen 7 5800H SMT')
    plt.plot(data_frame_amd['Линейные_Цели'], data_frame_amd['Линейный_OMP'], 'yo-', label='Amd Ryzen 7 5800H No SMT')
    plt.plot(data_frame_intel_smt['Линейные_Цели'], data_frame_intel_smt['Линейный_OMP'], 'bo-', label='Intel i7 12700H SMT')
    plt.plot(data_frame_intel['Линейные_Цели'], data_frame_intel['Линейный_OMP'], 'co-', label='Intel i7 12700H No SMT')
    plt.xlabel('Количество поисков')
    plt.ylabel('Время (микросекунды)')
    plt.title('OpenMP версия линейного поиска (omp)')
    plt.legend()
    plt.grid(True)
    plt.savefig('linear_omp_comparison.png', dpi=300, bbox_inches='tight')
    plt.show()

    # 4. График для GPU версии (igpu)
    plt.figure(figsize=(10, 6))
    plt.plot(data_frame_amd_smt['Линейные_Цели'], data_frame_amd_smt['Линейный_GPU'], 'ro-', label='Amd Ryzen 7 5800H SMT')
    plt.plot(data_frame_amd['Линейные_Цели'], data_frame_amd['Линейный_GPU'], 'yo-', label='Amd Ryzen 7 5800H No SMT')
    plt.plot(data_frame_intel_smt['Линейные_Цели'], data_frame_intel_smt['Линейный_GPU'], 'bo-', label='Intel i7 12700H SMT')
    plt.plot(data_frame_intel['Линейные_Цели'], data_frame_intel['Линейный_GPU'], 'co-', label='Intel i7 12700H No SMT')
    plt.xlabel('Количество поисков')
    plt.ylabel('Время (микросекунды)')
    plt.title('GPU версия линейного поиска (igpu)')
    plt.legend()
    plt.grid(True)
    plt.savefig('linear_igpu_comparison.png', dpi=300, bbox_inches='tight')
    plt.show()

binary_plot(
    csv_file_amd_smt="search_results_with_openCL_amd_smt.csv",
    csv_file_intel_smt="search_results_with_openCL_intel_smt.csv",
    csv_file_amd="search_results_with_openCL_amd.csv",
    csv_file_intel="search_results_with_openCL_intel.csv")

linear_plot(
    csv_file_amd_smt="search_results_with_openCL_amd_smt.csv",
    csv_file_intel_smt="search_results_with_openCL_intel_smt.csv",
    csv_file_amd="search_results_with_openCL_amd.csv",
    csv_file_intel="search_results_with_openCL_intel.csv")