CREATE OR REPLACE FUNCTION GENERATE_INSERT_COMMAND(p_id NUMBER)
RETURN VARCHAR2 IS
    v_val NUMBER;
    v_sql VARCHAR2(500);
BEGIN
    SELECT val INTO v_val FROM MYTABLE WHERE p_id = id;

    v_sql := 'INSERT INTO MyTable VALUES (' || p_id || ', ' || v_val || ');';
    DBMS_OUTPUT.PUT_LINE(v_sql);

    RETURN v_sql;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'ERROR! id = ' || p_id || ' not found in MyTable!';
    WHEN OTHERS THEN
        RETURN 'ERROR: ' || SQLERRM;
END GENERATE_INSERT_COMMAND;

SELECT '-1' AS input_value, GENERATE_INSERT_COMMAND(-1) AS result FROM dual
UNION ALL
SELECT '0', GENERATE_INSERT_COMMAND(0) FROM dual
UNION ALL
SELECT '1', GENERATE_INSERT_COMMAND(1) FROM dual
UNION ALL
SELECT '10000', GENERATE_INSERT_COMMAND(10000) FROM dual
UNION ALL
SELECT '10001', GENERATE_INSERT_COMMAND(10001) FROM dual;
